name: Performance improvement
description: 성능 개선, 리렌더링/속도/메모리 최적화
title: '[Perf] '
labels: ['type: perf']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ⚡ 개선 대상
        성능 문제가 되는 지점을 설명해주세요.

  - type: textarea
    id: perf-problem
    attributes:
      label: 문제 상황
      placeholder: |
        * 느린 구간
        * 병목 지점
        * 체감되는 문제
    validations:
      required: true

  - type: textarea
    id: perf-goal
    attributes:
      label: 개선 목표
      placeholder: |
        * 응답 시간 감소
        * 렌더링 횟수 감소
        * 메모리 사용 개선 등
    validations:
      required: true

  - type: textarea
    id: measurement
    attributes:
      label: 측정 기준 (선택)
      placeholder: |
        * Lighthouse
        * React Profiler
        * before / after 수치
    validations:
      required: false
