# Workers 관련
name = "joka-api-v1"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

# workers.dev 서브도메인 유지 (로컬용)
workers_dev = true

# 커스텀 도메인
[[routes]]
pattern = "api.mindjuk.quest"
custom_domain = true

# Auth KV 네임스페이스 바인딩
[[kv_namespaces]]
binding = "AUTH_TOKENS"
id = "056bed64ceed4ffaac3feea145363211"
preview_id = "056bed64ceed4ffaac3feea145363211"

# Hyperdrive
[[hyperdrive]]
binding = "HYPERDRIVE"
id = "b620191d4d484662be45eff46fd9b692"
localConnectionString = "postgres://admin:my-very-secure-pw@localhost:5432/mindjuk"

# 썸네일 추출 큐 producer 바인딩(consumer는 nail-artist)
[[queues.producers]]
queue = "thumbnail-jobs"
binding = "THUMBNAIL_QUEUE"

# 일반 환경 변수
[vars]
AUTH_SUCCESS_REDIRECT = "https://joka.mindjuk.quest"
ALLOWED_ORIGINS = "https://joka.mindjuk.quest,http://localhost:5173"
COOKIE_DOMAIN = ".mindjuk.quest"

# 로컬 관련
[dev]
port = 54861
local_protocol = "http"
